@Host = http://localhost:5063

POST {{Host}}/api/contacts
Content-Type: application/json

{
    "firstName": "Elyor",
    "lastName": "Khatanboyev",
    "phoneNumber": "+998999999999",
    "email": "Elyor99@gmail.com",
}

###
GET {{Host}}/api/contacts
###
GET {{Host}}/api/contacts/4
###
PUT {{Host}}/api/contacts/10
Content-Type: application/json

{
  "firstName": "Elyor",
  "lastName": "Khatanboyev",
  "phoneNumber": "+998999999999",
  "email": "Elyor99@gmail.com"
}
###
PATCH  {{Host}}/api/contacts/1
Content-Type: application/json

{
  "phoneNumber": "+998999999998"
}
###
DELETE  {{Host}}/api/contacts/3
###